name: Reminder Check
on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger notification check
        env:
          VERCEL_URL: ${{ secrets.VERCEL_URL }}
        run: |
          curl -X POST https://$VERCEL_URL/check-notifications \
          -H "Content-Type: application/json" \
          --fail --retry 3 --retry-delay 5 \
          || echo "Failed to trigger notification check"